### ISSUE TITLE
Game crashes when there's more then 1 player in a course (Peach's Castle works fine in every room)

### ISSUE THREAD

**Issue by GlitchyDorime** [djoslin0/sm64ex-coop#130] opened 2022-02-07 23:04 UTC
**Describe the bug**
As the tittle says, the game crashes when there's more then 1 player in a course, however, this doesn't happen in Peach's Castle (this also includes the Garden/Fountain zone and the Castle Grounds), as far as I know, this only happens on the 32-bit version of the game meanwhile in the 64-bit version of the game it works fine (many friends had told me about this not happening in 64-bit). This also happens in older versions of SM64ex-coop unstable.

**To Reproduce**
Steps to reproduce the crash:
1. Go to a course in the **32-bit** version with another player.
2. Select and enter that star.
3. Wait a few seconds, and the game will crash.

**Screenshots**
Can't take screenshots as the game closes immediately. 

**Desktop:**
 - Windows 10 [32-bit]

**Comment by djoslin0** [comment] 2022-02-10 08:05
Could you explain details? I can't get a crash to happen.
What settings are you using to build?
What do you have selected on the builder?
Are the people you are playing with in 64-bit or 32-bit mode?
Are you playing through Discord?
Which levels do you crash in?
What is the minimum set of steps to reproduce the crash?
Thanks

**Comment by GlitchyDorime** [comment] 2022-02-10 19:13
The only details I can explain is that it crashes on every course (incluiding secret courses as Peach's Secret Slide) and that it doesn't matter if you enter a star with already a player in it, or if another player enters after you entered, it will crash.
For the settings, speed is set to Ultra, render API is set to DirectX 11 and the version of the ROM is american.
![image](https://user-images.githubusercontent.com/80647077/153478334-95361981-8ef7-4001-b0b2-b1bfd3e8febc.png)
I've only played like 3 or 4 times with a friend that has the 32-bit version (or "mode") of the game, but most of the time it has been with 64-bit people, I don't know if it still crashes if I'm playing only with people with the same 32-bit version as I didn't tried to test it yet.
I'm playing trough Discord.
Again, it crashes on every course (or well, at least the ones that I've tried), I'm not sure if it also happens when entering a course with a loading zone and going trough it (like with Dire Dire Docks, that has one at half way on the tunnel or the pipes from Tiny Huge Island).
I didn't understand very well the last question as in the Issue comment the steps are there.
This is all of the information I know about this crash, sorry that I didn't answered the last question.

**Comment by djoslin0** [comment] 2022-02-11 03:03
Try now, I fixed at least one crash lol

**Comment by GlitchyDorime** [comment] 2022-02-11 17:08
It's kinda fixed now, it **still** crashes sometimes when I enter a course that has a player in it, but when I enter a course that doesn't have a player in it, and then someone enters to the same one, it **doesn't** crash!!
So yeah, you fixed one crash at least lol, tysm!
If you get to fix the other one (the first crash I've mentioned in this comment), please tell me

**Comment by djoslin0** [comment] 2022-02-12 03:10
Can you make sure all players recompile (a clean recompile) and test again? I thought the change only needed x86 people to recompile but it looks like x64 need to as well

**Comment by GlitchyDorime** [comment] 2022-02-17 23:51
Hi!, sorry for the REALLY late response, _been really busy this week_, but the thing is I didn't got to test it with someone that has a 32 bits PC, but I did test it on build 16 with a person that has a 64 bits PC, the two of us played the 3rd Bowser stage (**Bowser In The Sky**), and it didn't crash, we both got to play the whole stage itself even when dying and entering the two together (the first time I've entered first then the other player, and the second time I've entered after the other player did), until we both reached the Bowser Fight, where it crashed (this is the picture of the crash handler or whatever is called)
![image](https://user-images.githubusercontent.com/80647077/154586617-a8d2b74c-8112-4a37-8ec6-4a33c4e985f8.png)
I'm not sure if this is a crash that is related to the "more then 1 Player in a course" crash, or if it is another one
After that, I entered a game with the same guy from before and tried another level, and it didn't crash! (at least that was on Tall Tall Mountain, Snowman's Land, Bob Bomb Battlefield and Lethal Lava Land, it crashed with Rainbow Road)
![image](https://user-images.githubusercontent.com/80647077/154591007-3e129ccd-206a-4098-9033-65197b2bdc5c.png)

**Comment by djoslin0** [comment] 2022-02-19 03:53
The crash in the first picture should be fixed. The second picture didn't have enough in it for me to fix it unfortunately. Did a message box pop up before the crash screen showed up for that second picture?

**Comment by GlitchyDorime** [comment] 2022-02-19 12:57
Nope, I've saw that me and the other player entered together and then the crash handler screen showed up, we didn't even touched the ground.

**Comment by djoslin0** [comment] 2022-05-08 23:45
I believe this crash was fixed a while ago

**Closed by djoslin0** 2022-05-08 23:45 UTC
Labels: can not reproduce, crash
