### ISSUE TITLE
Loading zone teleport in DDD

### ISSUE THREAD

**Issue by eros71-dev** [djoslin0/sm64ex-coop#79] opened 2020-10-12 22:57 UTC
**Describe the bug**
When Mario (in my case) goes to the loading zone in DDD, Luigi will get teleported to him, but now he (Luigi) won't be able to leave that zone. As soon as Luigi tries to get out, both player will be sent to the tunnel again.

**To Reproduce**
1. Go to DDD
2. As Mario, go to the tunnel that connects to the submarine part of the level. (Make sure Luigi is not in there, as you may not be able to reproduce the bug if that happens.)
3. If Luigi tries to leave the tunnel, both players will get teleported to the tunnel again, like Luigi did when Mario entered the first time. 

**Expected behavior**
Both Mario and Luigi should be able to leave the tunnel.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/16540103/95797063-d332be80-0cee-11eb-930d-963bf24e1941.png)
![imagen](https://user-images.githubusercontent.com/16540103/95797078-dc239000-0cee-11eb-9a4e-ca46bfaa815d.png)

![imagen](https://user-images.githubusercontent.com/16540103/95797379-b3e86100-0cef-11eb-8768-08a2369258b4.png)
_The camera will glitch out if Mario gets teleported back._

**Additional context**
This bug can also cause some other artifacts, like Mario sliding on an invisible koopa shell in the air until he touches the water for some reason. (Could not get a screenshot of that sadly.)
Also, Mario seems to be able to move through the level as long as Luigi stays in there.

**Comment by anuserlol** [comment] 2020-10-12 23:05
Now that we realized, this is probably not a bug either.

**Comment by djoslin0** [comment] 2020-10-13 04:06
The camera is a bug, but the teleport behavior sounds like it's performing as it should. DDD is split into two different 'areas', players must be in the same area. There is an invisible warp/loading zone in that tunnel. To prevent race conditions, I don't allow players to go right back through the instant warp. I think there is a 10 second or so cooldown before it will allow them to go back

**Comment by djoslin0** [comment] 2022-02-27 07:00
fixed in latest unstable

**Closed by djoslin0** 2022-02-27 07:00 UTC
Labels: bug
