### ISSUE TITLE
Incorrect footstep sounds.

### ISSUE THREAD

**Issue by L0um15** [djoslin0/sm64ex-coop#97] opened 2021-02-16 12:23 UTC
**Describe the bug**
Grass should sound like a grass, not like a metalic surface.

**To Reproduce**
Many things affects variety of sounds: 
 - Diving into the wall,
 - kicking the wall, 
 - swimming 
 - sliding (seems to fix those issues).

**Expected behavior**
Clearly this should not be happening. These sounds are painfully loud and out of place.

**Screenshots**
I prepared a video showcase of this issue.
https://youtu.be/CVv_Rtm1fDw

**Desktop (please complete the following information):**
 - Windows 10 LTSC 2019 v1809

**Comment by camthesaxman** [comment] 2021-03-14 22:21
I am getting this same bug, though it only occurs on 32-bit builds (both Windows and Linux). 64-bit builds are unaffected. The original sm64ex (both 32-bit and 64-bit) is also unaffected.

**Comment by L0um15** [comment] 2021-03-15 07:28
Indeed, i forgot to mention that i used  32-bit version with default parameters except gl-legacy api renderer

**Comment by camthesaxman** [comment] 2021-03-16 02:29
I tested some commits and found that the sound is broken on 32-bit builds after commit d1739648e110d094c433c4686191f1f2b2628ad6. I am still investigating the cause.

**Comment by camthesaxman** [comment] 2021-03-16 02:43
Upon further investigation, it seems that the addition of the "26_custom_luigi" and "27_custom_luigi_peach" sound banks to "00_sound_player" in sequences.json has something to do with it. If I remove them, the footstep sounds play normally.

**Comment by L0um15** [comment] 2021-03-16 10:33
> I tested some commits and found that the sound is broken on 32-bit builds starting with commit [d173964](https://github.com/djoslin0/sm64ex-coop/commit/d1739648e110d094c433c4686191f1f2b2628ad6). I am still investigating the cause.

I assumed so too by checking commit history, but I didn't have time to test it.
However even if i do, i cant understand python so this would be a hard time for me.

**Comment by camthesaxman** [comment] 2021-03-17 00:08
I found the cause of the problem. Not enough memory is being given to the audio heap for persistent banks, so a few soundAlloc calls (including the ones that load the footstep sounds) are failing.

**Comment by L0um15** [comment] 2021-03-17 08:57
Nice, i will compile your fix and check if problem persists when i will have some time to spare.

**Comment by L0um15** [comment] 2021-03-17 09:45
Thank you!

**Comment by djoslin0** [comment] 2022-02-27 06:59
fixed in latest unstable

**Closed by djoslin0** 2022-02-27 06:59 UTC
